package org.apache.ddlutils.io;

import org.apache.commons.lang.exception.NestableRuntimeException;

/**
 * Exception generated by {@link org.apache.ddlutils.io.DataSink} implementations.
 */
public class DataSinkException extends NestableRuntimeException
{
    /**
     * Creates a new exception object.
     */
    public DataSinkException()
    {
        super();
    }

    /**
     * Creates a new exception object.
     * 
     * @param message The exception message
     */
    public DataSinkException(String message)
    {
        super(message);
    }

    /**
     * Creates a new exception object.
     * 
     * @param baseEx The base exception
     */
    public DataSinkException(Throwable baseEx)
    {
        super(baseEx);
    }

    /**
     * Creates a new exception object.
     * 
     * @param message The exception message
     * @param baseEx  The base exception
     */
    public DataSinkException(String message, Throwable baseEx)
    {
        super(message, baseEx);
    }
}
